[server]
host = "0.0.0.0"
port = 8080

[logging]
level = "debug"
file_path = "logs/mcp-gateway.log"
console_output = true

[database]
url = "mysql://dev:4qC8xGIjD@dev-mysql.starcharge.cloud:3306/mcp_swagger"
max_connections = 5
mcp_call_max_connections = 2

[embedding]
model_type = "simple"
dimension = 1024
vector_type="elasticsearch"

[embedding.elasticsearch]
host = "172.20.102.33"
port = "9200"
user = "elastic"
password = "elastic"

[embedding.aliyun]
api_key = "sk-147da3d9a37545c19010d27dcc5fcdb4"
model = "text-embedding-v4"
endpoint = "https://dashscope.aliyuncs.com/api/v1/services/embeddings/text-embedding/text-embedding"